export const color = {
  'primary-base': 'var(--color-primary-base)',
  'primary-light': 'var(--color-primary-light)',
  'primary-mlt': 'var(--color-primary-mlt)',
  'primary-mdk': 'var(--color-primary-mdk)',
  'primary-dark': 'var(--color-primary-dark)',
  'secondary-base': 'var(--color-secondary-base)',
  'secondary-light': 'var(--color-secondary-light)',
  'secondary-mlt': 'var(--color-secondary-mlt)',
  'secondary-mdk': 'var(--color-secondary-mdk)',
  'secondary-dark': 'var(--color-secondary-dark)',
  'tertiary-base': 'var(--color-tertiary-base)',
  'tertiary-light': 'var(--color-tertiary-light)',
  'tertiary-mlt': 'var(--color-tertiary-mlt)',
  'tertiary-mdk': 'var(--color-tertiary-mdk)',
  'tertiary-dark': 'var(--color-tertiary-dark)',
  'neutral-base': 'var(--color-neutral-base)',
  'neutral-light': 'var(--color-neutral-light)',
  'neutral-mlt': 'var(--color-neutral-mlt)',
  'neutral-mdk': 'var(--color-neutral-mdk)',
  'neutral-dark': 'var(--color-neutral-dark)',
  'success-base': 'var(--color-success-base)',
  'success-light': 'var(--color-success-light)',
  'success-mlt': 'var(--color-success-mlt)',
  'success-mdk': 'var(--color-success-mdk)',
  'success-dark': 'var(--color-success-dark)',
  'error-base': 'var(--color-error-base)',
  'error-light': 'var(--color-error-light)',
  'error-mlt': 'var(--color-error-mlt)',
  'error-mdk': 'var(--color-error-mdk)',
  'error-dark': 'var(--color-error-dark)',
  'warning-base': 'var(--color-warning-base)',
  'warning-light': 'var(--color-warning-light)',
  'warning-mlt': 'var(--color-warning-mlt)',
  'warning-mdk': 'var(--color-warning-mdk)',
  'warning-dark': 'var(--color-warning-dark)',
  'page-base': 'var(--color-page-base)',
  'page-light': 'var(--color-page-light)',
  'page-mlt': 'var(--color-page-mlt)',
  'page-mdk': 'var(--color-page-mdk)',
  'page-dark': 'var(--color-page-dark)',
  'page-contrast-base': 'var(--color-page-contrast-base)',
  'page-contrast-light': 'var(--color-page-contrast-light)',
  'page-contrast-mlt': 'var(--color-page-contrast-mlt)',
  'page-contrast-mdk': 'var(--color-page-contrast-mdk)',
  'page-contrast-dark': 'var(--color-page-contrast-dark)',
  'surface-base': 'var(--color-surface-base)',
  'surface-light': 'var(--color-surface-light)',
  'surface-mlt': 'var(--color-surface-mlt)',
  'surface-mdk': 'var(--color-surface-mdk)',
  'surface-dark': 'var(--color-surface-dark)',
  'surface-contrast-base': 'var(--color-surface-contrast-base)',
  'surface-contrast-light': 'var(--color-surface-contrast-light)',
  'surface-contrast-mlt': 'var(--color-surface-contrast-mlt)',
  'surface-contrast-mdk': 'var(--color-surface-contrast-mdk)',
  'surface-contrast-dark': 'var(--color-surface-contrast-dark)',
  'surface-raised-base': 'var(--color-surface-raised-base)',
  'surface-raised-light': 'var(--color-surface-raised-light)',
  'surface-raised-mlt': 'var(--color-surface-raised-mlt)',
  'surface-raised-mdk': 'var(--color-surface-raised-mdk)',
  'surface-raised-dark': 'var(--color-surface-raised-dark)',
  'surface-raised-contrast-base': 'var(--color-surface-raised-contrast-base)',
  'surface-raised-contrast-light': 'var(--color-surface-raised-contrast-light)',
  'surface-raised-contrast-mlt': 'var(--color-surface-raised-contrast-mlt)',
  'surface-raised-contrast-mdk': 'var(--color-surface-raised-contrast-mdk)',
  'surface-raised-contrast-dark': 'var(--color-surface-raised-contrast-dark)',
  'page-base': 'var(--color-page-base)',
  'page-light': 'var(--color-page-light)',
  'page-mlt': 'var(--color-page-mlt)',
  'page-mdk': 'var(--color-page-mdk)',
  'page-dark': 'var(--color-page-dark)',
  'page-contrast-base': 'var(--color-page-contrast-base)',
  'page-contrast-light': 'var(--color-page-contrast-light)',
  'page-contrast-mlt': 'var(--color-page-contrast-mlt)',
  'page-contrast-mdk': 'var(--color-page-contrast-mdk)',
  'page-contrast-dark': 'var(--color-page-contrast-dark)',
  'surface-base': 'var(--color-surface-base)',
  'surface-light': 'var(--color-surface-light)',
  'surface-mlt': 'var(--color-surface-mlt)',
  'surface-mdk': 'var(--color-surface-mdk)',
  'surface-dark': 'var(--color-surface-dark)',
  'surface-contrast-base': 'var(--color-surface-contrast-base)',
  'surface-contrast-light': 'var(--color-surface-contrast-light)',
  'surface-contrast-mlt': 'var(--color-surface-contrast-mlt)',
  'surface-contrast-mdk': 'var(--color-surface-contrast-mdk)',
  'surface-contrast-dark': 'var(--color-surface-contrast-dark)',
  'surface-raised-base': 'var(--color-surface-raised-base)',
  'surface-raised-light': 'var(--color-surface-raised-light)',
  'surface-raised-mlt': 'var(--color-surface-raised-mlt)',
  'surface-raised-mdk': 'var(--color-surface-raised-mdk)',
  'surface-raised-dark': 'var(--color-surface-raised-dark)',
  'surface-raised-contrast-base': 'var(--color-surface-raised-contrast-base)',
  'surface-raised-contrast-light': 'var(--color-surface-raised-contrast-light)',
  'surface-raised-contrast-mlt': 'var(--color-surface-raised-contrast-mlt)',
  'surface-raised-contrast-mdk': 'var(--color-surface-raised-contrast-mdk)',
  'surface-raised-contrast-dark': 'var(--color-surface-raised-contrast-dark)'
}
export const btn = {
  'p-sm': '0.4rem 1.2000000000000002rem',
  'p-base': '0.5rem 1.5rem',
  'btn-chip-p': '0.25rem 0.75rem',
  'p-lg': '0.6rem 1.7999999999999998rem'
}
export const ui = {
  rounded: 'var(--radius-md)',
  'button-roundness': 'var(--radius-full)',
  'input-roundness': 'var(--radius-full)'
}
